- cpu_comparisons/linear_regression_demo.ipynb
I noticed that when we were using the randomly generated data we were missing the code for randomly generating the target variables so i added this line to fix that.
> Updated code for y when ds is missing

- tutorials/KDD-2019/KDD-2019.md
Added placeholder for KDD tutorial material so that link can be used in proposal
> [REVIEW] KDD 2019 placeholder

- blogs/Regression Blog 1 Notebook.ipynb
This is from the medium post I did.
> blog from regression notebook

- beginner/basics/Dask_Hello_World.ipynb
- beginner/basics/Getting_Started_with_Dask.ipynb
- beginner/basics/Getting_Started_with_cuDF.ipynb
addressing issues 
https://github.com/rapidsai/notebooks/issues/165
https://github.com/rapidsai/notebooks/issues/163
https://github.com/rapidsai/notebooks/issues/162
> Khcs errors

- advanced/conf_notebooks/GTC/GTC_tutorial_instructor.ipynb
- advanced/conf_notebooks/GTC/GTC_tutorial_student.ipynb
These are the the two notebooks I taught I my session 1, day 1 RAPIDS tutorial from during GTC San Jose 2019.
> gtc tutorial notebooks

- colab_notebooks/DBScan_colab_nightlies.ipynb
- colab_notebooks/coordinate_descent_demo_colab_nightlies.ipynb
added 2 more notebooks.   5 more to update and add!
> Colab coord

- colab_notebooks/Louvain_Colab.ipynb
- colab_notebooks/Vertex_Similarity_Colab.ipynb
- colab_notebooks/Weighted_Jaccard_Colab.ipynb
Added Colab versions for: 
Louvain,
Weighted Jaccard,
Vertex Similarity.
> Added Colab Notebooks

- intermediate_notebooks/examples/census_education2income_demo.ipynb
> added census notebook

- getting_started_notebooks/basics/streamz_weblogs.ipynb
This pr aims to update the streamz notebook, primarily tackling the file handling aspect of the Streamz-weblogs notebook.
Updates include:
- Updated logic to read and remove headers from original file
- Updated logic to handle both bytes and str like messages in `process_on_gpu`
> [REVIEW] Updates to Streamz notebooks

- multimedia_links.md
Contains videos from various sources, presenting conference, studio, and in-the-works style info regarding RAPIDS AI and/or GPU computing
- RAPIDS AI ([playlist](https://youtube.com/playlist?list=PLe8uB6iJZSca7RdGIU52xKFyLCbEJhzAF))
- Collection of videos related to RAPIDS AI -- Open GPU Data Science
> Add "RAPIDS AI" yt playlist to Community Playlists

- .gitignore
Add .ipynb_checkpoints, as in /notebooks
> Update .gitignore (checkpoints)

- colab_notebooks/.ipynb_checkpoints/COLAB README-checkpoint.md
> Delete COLAB README-checkpoint.md

- getting_started_notebooks/basics/streamz_weblogs.ipynb
> [REVIEW] Updates to streamz_weblogs

- colab_notebooks/census.ipynb
@taureandyernv New link to data
> Updated census.ipynb

- competition_notebooks/kaggle/plasticc/notebooks/rapids_lsst_gpu_only_demo.ipynb
> Add more blog links

- colab_notebooks/README.md
- fix contributing link 
- from notebooks-extended to notebooks-contrib
- remove redundant chrome store link
> Update /colab_notebooks README.md (-contrib name change)

- colab_notebooks/black_friday- GTC presentation remix for meetups.ipynb
> Create black_friday- GTC presentation remix for meetups.ipynb

- utils/rapids-colab.sh
My [previous PR](https://github.com/rapidsai/notebooks-contrib/pull/110) was from the wrong branch.
This should fix the ability to install previous versions. I've tested with 0.9 and 0.8.
@taureandyernv fyi
> [BUG] Second PR to fix Colab install script, actually support multiple versions via arg

- intermediate_notebooks/E2E/census/census_education2income_demo.ipynb
updated MSE and CoD code due to api changes
> Update MSE and CoD code due to api changes

- utils/rapids-colab.sh
Fixing Colab install script to pull cudf 0.10 compatible XGBoost package from pip
Also removed dead dask-cuml package
> rapids-colab.sh install script fixes

- blog_notebooks/plasticc/Dockerfile
- blog_notebooks/plasticc/README.md
- blog_notebooks/plasticc/data/README.md
- blog_notebooks/plasticc/notebooks/.kaggle/kaggle.json
- blog_notebooks/plasticc/notebooks/cudf_workaround.py
- blog_notebooks/plasticc/notebooks/rapids_lsst_full_demo.ipynb
- blog_notebooks/plasticc/notebooks/rapids_lsst_gpu_only_demo.ipynb
adding back these notebooks that somehow got removed in the PR madness
> re-adding lost plasticc notebooks

- blog_notebooks/cuspatial/trajectory_clustering.ipynb
Fixes #201 
Add the changes from https://github.com/rapidsai/notebooks/pull/218 and validate everything works.
I forgot to move the correct data file, as well.
> Update repo and add data file back where it belongs.

- intermediate_notebooks/E2E/synthetic_3D/rapids_ml_workflow_demo.ipynb
> Fixed Inconsistent Tree Depth

- colab_notebooks/README.md
- colab_notebooks/cuml/README.md
Add directory **Layout** section to `colab_notebooks/README.md` 
- and slight adjustments to **Using Colab Notebooks** for improved readability
Resolves #205
> [REVIEW] Update colab_notebooks README.md

- blog_notebooks/azureml/README.md
- blog_notebooks/azureml/nyctaxi_data.py
- blog_notebooks/azureml/rapids/init_dask.py
- blog_notebooks/azureml/rapids/nyctaxi_demo.ipynb
- blog_notebooks/azureml/rapids/rapids-0.9.yml
- blog_notebooks/azureml/start_azureml.py
This adds a new notebook (based on the Taxi notebook) and supporting scripts for an upcoming blog. Code is by @mt-jones originall in https://github.com/mt-jones/RAPIDS-AzureML, but we're adding it here to centralize with official RAPIDS content.
> [REVIEW] Add content for upcoming RAPIDS on Azure Machine Learning blog

- blog_notebooks/nlp/show_me_the_word_count_gutenberg/show_me_the_word_count_gutenberg.ipynb
This pr fixes issue https://github.com/rapidsai/notebooks-contrib/issues/221
> [Review] Fix issue 221 on show_me_the_word_count_gutenberg

- utils/env-check.py
- utils/rapids-colab.sh
adding P100 as a usable GPUs in colab script
> Adding P100 to colab script

- utils/rapids-colab.sh
Updates the version of `cuml` in the install file (` /utils/rapids-colab.sh`)
> Fixes #228

- blog_notebooks/cyber/flow_classification/flow_classification_rapids.ipynb
I'm not able to run the lanl notebook yet due to dependencies.
> [REVIEW] Fix flow classification notebook. Depends on cudf 3388

- blog_notebooks/cyber/flow_classification/flow_classification_rapids.ipynb
Putting new flow classification notebook in v0.11
> Fix flow classification notebook. Depends on cudf 3388

- blog_notebooks/cyber/flow_classification/flow_classification_rapids.ipynb
Reverts rapidsai/notebooks-contrib#231
> Revert "[REVIEW] Fix flow classification notebook. Depends on cudf 3388"

- utils/rapids-colab.sh
- utils/update_pyarrow.py
Pushes Colab Script Utils merge #233 that went into `master` into `branch-0.11` (and `branch-0.12`)
> update colab for v0.11

- utils/rapids-colab.sh
Still may need some additional edge cases, but if user is compliant, then it will work.
> Added user interface to Colab Script

- utils/rapids-colab.sh
removed accidentally added line
> quick fix on rapids-colab.sh

- utils/env-check.py
- utils/rapids-colab.sh
Colab has a new GPU and we have a new RAPIDS!
This updates
> [REVIEW] Updating colab to 0.11 stable and new GPU

- conference_notebooks/KDD_2020/notebooks/nvtabular/rossmann-store-sales-example.ipynb
- conference_notebooks/KDD_2020/nvtabular/rossmann-store-sales-example.ipynb
Updated the NVT KDD2020 notebook to work with the updated NVT APIs
> Updated KDD2020 NVT notebook to work with updated APIs

- conference_notebooks/KDD_2020/Presenters.md
- conference_notebooks/KDD_2020/README.md
fixed some typos, added Corey, and added links
> KDD 2020 Updated docs

- blog_notebooks/preprocessing/Preprocessing.ipynb
Provide initial version of notebook demonstrating new cuML preprocessing features
> [REVIEW] Add notebook used for preprocessing blog

- the_archive/archived_rapids_event_notebooks/KDD_2020/README.md
> update kdd 2020 readme as per PR #311

- getting_started_materials/intro_tutorials_and_guides/02_Introduction_to_cuDF.ipynb
close previous PR #301 , which is outdated, but made us check.  thanks @akanz1 !
> update a docs link

- community_tutorials_and_guides/weather.ipynb
Updated descriptions to focus on ease of use over history of development, as per @beckernick . Also fixed typos
> weather.ipynb: Updated text

- README.md
- getting_started_materials/README.md
> Add more community links

- getting_started_materials/hello_worlds/dask-sql/getting_started_with_dasksql.ipynb
Add in Sagemaker links
Verbiage fixes
> Update for 22.02

- README.md
Added blogs for Rapids Deploy on IBM Cloud under Cloud Service Provider
> [REVIEW] Add IBM cloud instructions to main README

- community_tutorials_and_guides/census_education2income_demo.ipynb
- community_tutorials_and_guides/cugraph/README.md
- community_tutorials_and_guides/cugraph/get_data.sh
- community_tutorials_and_guides/cugraph/multi_gpu_pagerank.ipynb
- the_archive/archived_rapids_benchmarks/cugraph_mg_hibench/multi_gpu_pagerank.ipynb
- the_archive/archived_rapids_blog_notebooks/cyber/flow_classification/flow_classification_rapids.ipynb
Update datasets download URL to reduce latency and costs
> Update datasets download URL

- getting_started_materials/intro_tutorials_and_guides/12_Introduction_to_Exploratory_Data_Analysis_using_cuDF.ipynb
- getting_started_materials/intro_tutorials_and_guides/13_Introduction_to_Time_Series_Data_Analysis_using_cuDF.ipynb
> fixed typo in the author's name

- community_tutorials_and_guides/cugraph/multi_gpu_pagerank.ipynb
> modified multi-gpu_pagerank to run with current cugraph environment and version

- community_tutorials_and_guides/census_education2income_demo.ipynb
Removes some rogue characters from `census_education2income_demo.ipynb` that were preventing the notebook from being opened.
Since I am running through the notebooks for WSL testing, can follow up in this branch with fixes to any other invalid notebooks.
> Fix invalid JSON in census demo notebook

- getting_started_materials/README.md
> update crash course
